### PR TITLE
Transport Producer Pool Test

### PR DESCRIPTION
**Pull request by albertodenatale**
Hi @jsquire @kinelski @ShivangiReja 
I am creating a pull request with the test run I used for the ```TransportProducerPool```.

It would not build now as it is referencing ```Azure.Messaging.EventHubs``` ```5.0.0-dev.*```.

If it is something you think might come useful we could merge it otherwise happy to close the pull request.

Thank you

### CODE REVIEW

**Comment by jsquire** [comment]
Sorry, @albertodenatale, this end up triggering the spam filter for some reason.    I definitely think having more scenarios hanging around is better than less.   I've give this a quick look and assuming all is well, pull it in.

**Review by jsquire — APPROVED** [review]
LGTM

**Comment by albertodenatale** [comment]
@jsquire my apologies just realised there was a hard reference in the solution and I removed it. I created a separate pull.

**Comment by jsquire** [comment]
All good.   This is a much more ad-hoc set of code with much looser conventions - hence why it lives in Caio's personal repository and the notifications get caught up in personal account spam filters.  😄

**Pull request merged**
